In [73]:
import torch
import numpy as np


# Initialize a tensor

In [5]:
tensor1 = torch.tensor([[1,2,3], [4,5,6]], dtype = torch.float32, device = "cuda", requires_grad = True)

print(tensor1)
print(tensor1.dtype)
print(tensor1.device)
print(tensor1.shape)
print(tensor1.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


In [62]:
# random tensor
tensor2 = torch.empty(size = (3,3))
print(f"tensor2:\n{tensor2}")
normal = torch.empty(size = (3,3)).normal_(mean = 0, std = 1)
print(f"normal:\n{normal}")
uniform = torch.empty(size = (3,3)).uniform_(0,1)
print(f"uniform:\n{uniform}")
zeros = torch.zeros((3,3))
print(f"zeros:\n{zeros}")
ones = torch.ones((3,3))
print(f"ones:\n{ones}")
rand = torch.rand((3,3))
print(f"rand:\n{rand}")
randint = torch.randint(low = 0, high = 10, size = (3,3))
print(f"randint:\n{randint}")

tensor2:
tensor([[3.4167e-25, 4.5715e-41, 3.4167e-25],
        [4.5715e-41, 4.4842e-44, 0.0000e+00],
        [1.7937e-43, 0.0000e+00, 5.9587e-06]])
normal:
tensor([[-0.9968, -0.6380,  0.1243],
        [-1.3596, -0.4762, -1.7377],
        [ 2.0015,  0.4611,  1.8804]])
uniform:
tensor([[0.9352, 0.4984, 0.2739],
        [0.5652, 0.2404, 0.3210],
        [0.4484, 0.5803, 0.2971]])
zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
ones:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
rand:
tensor([[0.4182, 0.8843, 0.0403],
        [0.7211, 0.5253, 0.0636],
        [0.8932, 0.3161, 0.0907]])
randint:
tensor([[2, 6, 2],
        [8, 2, 3],
        [9, 2, 5]])


In [64]:
arange = torch.arange(start = 0, end = 9, step = 1)
print(f"arange:\n{arange}")
arange = arange.reshape(3,3)
print(f"arange reshaped:\n{arange}")
linspace = torch.linspace(start = 0, end = 1, steps = 6, device= "cuda")
print(f"linspace:\n{linspace}")
diag = torch.diag(linspace)
print(f"diag:\n{diag}")

arange:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
arange reshaped:
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
linspace:
tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000], device='cuda:0')
diag:
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.2000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.4000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.6000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.8000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000]], device='cuda:0')


# Conversions

In [72]:
print(diag.bool().dtype)
print(diag.short().dtype)
print(diag.long().dtype)
print(diag.half().dtype)
print(diag.float().dtype)
print(diag.double().dtype)

torch.bool
torch.int16
torch.int64
torch.float16
torch.float32
torch.float64


In [76]:
npy = np.arange(0,9).reshape(3,3)
print(f"npy:\n{npy}")
trch = torch.from_numpy(npy)
print(f"trch:\n{trch}")
npy_again = trch.numpy()
print(f"npy_again:\n{npy_again}")

npy:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
trch:
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
npy_again:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Operations

In [86]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

z1 = torch.empty(3)
torch.add(x,y, out = z1)
print(f"z1:\n{z1}")

z2 = torch.add(x,y)
print(f"z2:\n{z2}")

z3 = x + y
print(f"z3:\n{z3}")

t = torch.zeros(3)
t.add(x)
print(f"t:\n{t}")
# inplace: t += x is not equal t = t + x
t.add_(x)
print(f"t:\n{t}")


z1:
tensor([10., 10., 10.])
z2:
tensor([10, 10, 10])
z3:
tensor([10, 10, 10])
t:
tensor([0., 0., 0.])
t:
tensor([1., 2., 3.])


In [143]:
# 1D
x = torch.tensor([2,3,1,4,1])
y = torch.tensor([1,2,3,4,5])

z = torch.dot(x,y)
print(f"z:\n{z}")

z = x @ y
print(f"z:\n{z}")

z:
32
z:
32


In [144]:
# 2
x = torch.rand((2,5))
y = torch.rand((5,3))

z = torch.mm(x,y)
print(f"z:\n{z}")


z = x.mm(y)
print(f"z:\n{z}")

z = x @ y
print(f"z:\n{z}")

# # ERROR: element wise
# z = x * y
# print(f"z:\n{z}")

# instead:
x = torch.rand((3,3))
y = torch.rand((3,3))

z = x * y
print(f"z:\n{z}")

z = x @ y
print(f"z:\n{z}")

z:
tensor([[0.8868, 2.0470, 1.5151],
        [0.5392, 0.8343, 1.1270]])
z:
tensor([[0.8868, 2.0470, 1.5151],
        [0.5392, 0.8343, 1.1270]])
z:
tensor([[0.8868, 2.0470, 1.5151],
        [0.5392, 0.8343, 1.1270]])
z:
tensor([[0.2107, 0.0378, 0.1753],
        [0.4744, 0.1163, 0.1511],
        [0.1202, 0.1195, 0.3205]])
z:
tensor([[0.3688, 0.4763, 0.5389],
        [1.0755, 0.5380, 1.1913],
        [0.4911, 0.7663, 0.6688]])


In [121]:
# power
matrix = torch.rand(5,5)
print(f"matrix:\n{matrix}")

# 1 == 2
matrix_exp1 = matrix.matrix_power(3)
print(f"matrix_exp1:\n{matrix_exp1}")

matrix_exp2 = matrix @ matrix @ matrix
print(f"matrix_exp2:\n{matrix_exp2}")

# 3 == 4
matrix_exp3 = matrix ** 3
print(f"matrix_exp3:\n{matrix_exp3}")

matrix_exp4 = matrix * matrix * matrix
print(f"matrix_exp4:\n{matrix_exp4}")


matrix:
tensor([[0.0806, 0.5150, 0.0487, 0.3116, 0.2570],
        [0.4916, 0.7937, 0.8312, 0.0028, 0.1828],
        [0.5941, 0.5320, 0.5506, 0.2423, 0.4159],
        [0.2774, 0.8302, 0.6802, 0.5599, 0.0320],
        [0.5852, 0.0746, 0.1801, 0.0715, 0.5306]])
matrix_exp1:
tensor([[1.0677, 1.4633, 1.2550, 0.4892, 0.7278],
        [1.9622, 2.5830, 2.1941, 0.8692, 1.3902],
        [1.8434, 2.4776, 2.1038, 0.8667, 1.2851],
        [2.2274, 3.1058, 2.6958, 1.0312, 1.4716],
        [0.9036, 1.1782, 0.9719, 0.4526, 0.6614]])
matrix_exp2:
tensor([[1.0677, 1.4633, 1.2550, 0.4892, 0.7278],
        [1.9622, 2.5830, 2.1941, 0.8692, 1.3902],
        [1.8434, 2.4776, 2.1038, 0.8667, 1.2851],
        [2.2274, 3.1058, 2.6958, 1.0312, 1.4716],
        [0.9036, 1.1782, 0.9719, 0.4526, 0.6614]])
matrix_exp3:
tensor([[5.2285e-04, 1.3656e-01, 1.1544e-04, 3.0248e-02, 1.6978e-02],
        [1.1880e-01, 4.9991e-01, 5.7430e-01, 2.2988e-08, 6.1119e-03],
        [2.0964e-01, 1.5058e-01, 1.6695e-01, 1.4226e-02, 7.1

In [150]:
# batch (3D)
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
print(f"tensor1:\n{tensor1}")

tensor2 = torch.rand((batch, m, p))
print(f"tensor2:\n{tensor2}")

tensor3 = torch.bmm(tensor1, tensor2)
print(f"tensor3:\n{tensor3}")

tensor4 = tensor1 @ tensor2
print(f"tensor3:\n{tensor4}")

(tensor3 == tensor4).all()


tensor1:
tensor([[[6.7570e-01, 8.8148e-01, 4.7191e-01,  ..., 8.7708e-01,
          9.9102e-01, 8.7039e-01],
         [1.7002e-01, 3.1173e-01, 7.2104e-01,  ..., 2.1294e-01,
          9.0533e-01, 1.0901e-01],
         [5.2329e-01, 7.5606e-01, 9.5476e-01,  ..., 9.3034e-01,
          9.0583e-01, 2.0702e-01],
         ...,
         [8.7069e-01, 6.1475e-01, 7.0004e-02,  ..., 8.9592e-01,
          3.7853e-01, 6.5807e-02],
         [5.5961e-01, 4.7173e-01, 4.3900e-01,  ..., 6.9896e-02,
          1.6311e-02, 3.5230e-01],
         [2.6892e-01, 7.1009e-01, 5.8577e-01,  ..., 2.4617e-01,
          2.8779e-01, 8.5792e-01]],

        [[2.2735e-01, 5.2786e-01, 7.8090e-01,  ..., 4.9412e-01,
          4.8139e-01, 6.0109e-01],
         [8.8605e-01, 8.0136e-01, 1.4503e-01,  ..., 3.2735e-02,
          3.4792e-01, 3.6975e-01],
         [4.5199e-01, 8.6711e-01, 9.1300e-01,  ..., 3.5526e-01,
          8.8713e-02, 6.7879e-01],
         ...,
         [8.6899e-01, 4.0100e-01, 5.8299e-01,  ..., 9.3225e-01,
      

tensor(True)

# Reshape

In [167]:
x = torch.arange(9)

# view must be contiguous in memory
x_3x3 = x.view(3,3)
print(f"x_3x3:\n{x_3x3}")

x_3x3 = x.reshape(3,3)
print(f"x_3x3:\n{x_3x3}")

y = x_3x3.T
print(f"y:\n{y}")


x_3x3:
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
x_3x3:
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
y:
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

# Cat

In [182]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))

print(torch.cat((x1,x2), dim = 0).shape)
print(torch.cat((x1,x2), dim = 1).shape)
print(torch.cat((x1,x2), dim = -1).shape)

print("*" * 30)

x = torch.arange(10)
print(f"x.shape:\n{x.shape}")
print(f"x.unsqueeze(0).shape:\n{x.unsqueeze(0).shape}")
print(f"x.unsqueeze(1).shape:\n{x.unsqueeze(1).shape}")
print(f"x.unsqueeze(-1).shape:\n{x.unsqueeze(-1).shape}")

print(f"x[:,None].shape:\n{x[:,None].shape}")
print(f"x[None,:].shape:\n{x[None,:].shape}")



torch.Size([4, 5])
torch.Size([2, 10])
torch.Size([2, 10])
******************************
x.shape:
torch.Size([10])
x.unsqueeze(0).shape:
torch.Size([1, 10])
x.unsqueeze(1).shape:
torch.Size([10, 1])
x.unsqueeze(-1).shape:
torch.Size([10, 1])
x[:,None].shape:
torch.Size([10, 1])
x[None,:].shape:
torch.Size([1, 10])
